routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\API\ChatAPIController;
use App\Http\Controllers\API\UserAPIController;

// login & logout route
Route::get('/', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'index']);
Route::get('login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'index'])->name('admin.login');
Route::post('login/authenticate', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'authenticate'])->name('admin.login.authenticate');
Route::get('logout', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('admin.logout');

// Forgot Password Route
Route::get('forgot-password/create', [\App\Http\Controllers\Admin\Auth\ForgotPasswordController::class, 'showForgotPasswordForm'])->name('admin.forgot_password.create');
Route::post('forgot-password/email/send', [\App\Http\Controllers\Admin\Auth\ForgotPasswordController::class, 'sendPasswordResetLink'])->name('admin.forgot_password.send');
Route::get('password/reset/{token}', [\App\Http\Controllers\Admin\Auth\ForgotPasswordController::class, 'resetPasswordForm'])->name('admin.password_reset.create');
Route::post('password/reset', [\App\Http\Controllers\Admin\Auth\ForgotPasswordController::class, 'passwordReset'])->name('admin.password_reset.store');


Route::middleware('admin')->group(function () {
    // Dashboard Route
    Route::get('dashboard', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

    Route::get('sync', [\App\Http\Controllers\Admin\UserController::class, 'syncIndex'])->name('admin.sync.index');
    Route::post('sync', [\App\Http\Controllers\Admin\UserController::class, 'syncSubmit'])->name('admin.sync.submit');

    // Chat
    Route::get('conversations-list-user', [ChatAPIController::class, 'getLatestConversationsForUesr']);
    Route::get('/conversations', [ChatController::class, 'index'])->name('adminConversations');
    Route::get('users/{id}/conversation', [UserAPIController::class,'getConversationForAdmin']);

    //User Routes
    Route::get('survey', [\App\Http\Controllers\Admin\DefinitionController::class, 'survey'])->name('admin.survey.list');
    Route::get('survey/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'surveyShow'])->name('admin.survey.show');

    Route::get('users', [\App\Http\Controllers\Admin\UserController::class, 'index'])->name('admin.users.list');
    Route::get('user/show/{id}', [\App\Http\Controllers\Admin\UserController::class, 'show'])->name('admin.user.show');
    Route::get('user/chat', [\App\Http\Controllers\Admin\UserController::class, 'showchat'])->name('admin.user.showchat');
    Route::delete('user/delete/{id}', [\App\Http\Controllers\Admin\UserController::class, 'destroy'])->name('admin.user.delete');


    // Site Configuration
    Route::get('configurations', [\App\Http\Controllers\Admin\SiteConfigurationController::class, 'index'])->name('admin.configurations');
    Route::post('configuration/update', [\App\Http\Controllers\Admin\SiteConfigurationController::class, 'update'])->name('admin.configuration.update');
    Route::post('configuration/remove/video', [\App\Http\Controllers\Admin\SiteConfigurationController::class, 'remove_video'])->name('admin.configuration.remove_video');

    // Subscription plans route
    Route::get('subscriptions', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'index'])->name('admin.subscriptions_plan.list');
    Route::get('subscription/create', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'create'])->name('admin.subscription_plan.create');
    Route::post('subscription/store', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'store'])->name('admin.subscription_plan.store');
    Route::get('subscription/edit/{id}', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'edit'])->name('admin.subscription_plan.edit');
    Route::post('subscription/update', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'update'])->name('admin.subscription_plan.update');
    Route::get('subscription/show/{id}', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'show'])->name('admin.subscription_plan.show');
    Route::delete('subscription/delete/{id}', [\App\Http\Controllers\Admin\SubscriptionPlanController::class, 'delete'])->name('admin.subscription_plan.delete');


    // Subscription routes
    Route::get('customer/subscriptions', [\App\Http\Controllers\Admin\CustomerSubscriptionController::class, 'index'])->name('admin.subscriptions.list');
    Route::get('customer/subscription/show/{id}', [\App\Http\Controllers\Admin\CustomerSubscriptionController::class, 'show'])->name('admin.subscription.show');
    Route::delete('customer/subscription/delete/{id}', [\App\Http\Controllers\Admin\CustomerSubscriptionController::class, 'delete'])->name('admin.subscription.delete');

    //Email Templates Routes
    Route::get('email/templates', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'index'])->name('admin.email_templates.list');
    Route::get('email/template/create', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'create'])->name('admin.email_template.create');
    Route::post('email/template/store', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'store'])->name('admin.email_template.store');
    Route::get('email/template/edit/{id}', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'edit'])->name('admin.email_template.edit');
    Route::post('email/template/update', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'update'])->name('admin.email_template.update');
    Route::delete('email/template/delete/{id}', [\App\Http\Controllers\Admin\EmailTemplateController::class, 'delete'])->name('admin.email_template.delete');


    //Contact Request
    Route::get('contact-requests', [\App\Http\Controllers\Admin\ContactRequestController::class, 'index'])->name('admin.contact_requests.list');
    Route::get('contact-request/show/{id}', [\App\Http\Controllers\Admin\ContactRequestController::class, 'show'])->name('admin.contact_request.show');
    Route::delete('contact-request/delete/{id}', [\App\Http\Controllers\Admin\ContactRequestController::class, 'destroy'])->name('admin.contact_request.delete');

    //Key Definition
    Route::get('alerts', [\App\Http\Controllers\Admin\DefinitionController::class, 'index'])->name('admin.alerts.list');

    Route::post('alerts/import', [\App\Http\Controllers\Admin\DefinitionController::class, 'importAlerts'])->name('admin.alerts.import');

    Route::get('alert/create', [\App\Http\Controllers\Admin\DefinitionController::class, 'create'])->name('admin.alert.create');
    Route::post('alert/store', [\App\Http\Controllers\Admin\DefinitionController::class, 'store'])->name('admin.alert.store');
    Route::get('alert/edit/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'edit'])->name('admin.alert.edit');
    Route::post('alert/update/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'update'])->name('admin.alert.update');
    Route::delete('alert/delete/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'delete'])->name('admin.alert.delete');
    Route::get('alert/show/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'show'])->name('admin.alert.show');

    Route::get('alert/tag/delete/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'deleteTag'])->name('tag.delete');
    Route::get('alert/sic/delete/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'deleteSic'])->name('sic.delete');
    Route::get('alert/symbol/delete/{id}', [\App\Http\Controllers\Admin\DefinitionController::class, 'deleteSymbol'])->name('symbol.delete');


    //Key Definition Mapping
    Route::get('key-alert-mapping',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'index'])->name('admin.key_alert_mapping.list');
    Route::get('key-alert-mapping/create',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'create'])->name('admin.key_alert_mapping.create');
    Route::post('key-alert-mapping/store',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'store'])->name('admin.key_alert_mapping.store');
    Route::get('key-alert-mapping/show/{id}',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'show'])->name('admin.key_alert_mapping.show');
    Route::get('key-alert-mapping/edit/{id}',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'edit'])->name('admin.key_alert_mapping.edit');
    Route::post('key-alert-mapping/update/{id}',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'update'])->name('admin.key_alert_mapping.update');
    Route::delete('key-alert-mapping/delete/{id}',[\App\Http\Controllers\Admin\KeyDefinitionMappingController::class,'delete'])->name('admin.key_alert_mapping.delete');

    Route::resource('companies', 'CompanyController', ['as' => 'admin']);

    Route::get('newsletter', [\App\Http\Controllers\Admin\UserController::class, 'newsLetter'])->name('admin.newsletter');
    Route::post('newsletterEmail', [\App\Http\Controllers\Admin\UserController::class, 'newsLetterEmail'])->name('admin.newsletteremail');
    Route::post('newsletterEmailAll', [\App\Http\Controllers\Admin\UserController::class, 'newsLetterEmailAll']);
    Route::post('newsletterEmailUpdate', [\App\Http\Controllers\Admin\UserController::class, 'newsletterEmailUpdate']);

    Route::get('cancel-survey-feedback', [\App\Http\Controllers\Admin\UserController::class, 'cancelSubscriptionFeedback'])->name('admin.cancel-survey-feedback');

});

routes/web.php
<?php

use App\Http\Controllers\Front\HomeController;
use App\Models\BalanceSheetStatement;
use App\Models\CashFlowStatement;
use App\Models\Company;
use App\Models\Definition;
use App\Models\MapperCikName;
use App\Services\FinancialModelingPrep;
use Carbon\Carbon;
use Goutte\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

use App\Http\Controllers\ChatController;
use App\Http\Controllers\API\UserAPIController;
use App\Http\Controllers\API\BlockUserAPIController;
use App\Http\Controllers\API\GroupAPIController;
use App\Http\Controllers\API\ChatAPIController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\API\NotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('user/email-verify/{token}', [App\Http\Controllers\Front\UserController::class, 'emailVerify'])->name('user.email_verification');
Route::get('get-alert/{identifier}', [\App\Http\Controllers\AlertController::class, 'getAlert']);
Route::get('pdf/{symbol}/earning-transcript', [HomeController::class, 'pdfTranscript'])->name('pdf');
Route::get('sub', [\App\Http\Controllers\Front\SubscriptionPlanController::class, 'index']);
$pageRoutes = [];
Route::get('/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name("home");
Route::get('earning-call-transcript/{symbol}/{quarter}/{year}', [App\Http\Controllers\Front\HomeController::class, 'showEarningTranscript'])->name("earning_call_transcript");

Route::get('data', [\App\Http\Controllers\Front\KeywordController::class, 'keyword']);
Route::get('/app', [App\Http\Controllers\Front\HomeController::class, 'app'])->name("app_main")->middleware('auth','privacyPolicy', 'user.activated');

Route::get('app/stock-details', [App\Http\Controllers\Front\HomeController::class, 'stockDetails'])->name('stock-details')->middleware('auth','privacyPolicy', 'user.activated');

Route::get('/chart/{symbol}', [App\Http\Controllers\Front\HomeController::class, 'chart'])->name("chart");

//Route::get('/messages', ['uses' => 'Front/MessagesController@index', 'as' => 'messages']);

// user registration route
Route::get('user/register', [\App\Http\Controllers\Front\UserController::class, 'register'])->name('user.register');
Route::get('user/welcome', [\App\Http\Controllers\Front\UserController::class, 'welcome'])->name('user.welcome')->middleware('auth');
Route::post('user/register/store', [App\Http\Controllers\Front\UserController::class, 'store'])->name('user.register.store');

Route::get('user/make-subscription/{id}', [App\Http\Controllers\Front\UserController::class, 'registerWithSocialite'])->name('user.make_subscription');
Route::post('user/make-subscription/store', [App\Http\Controllers\Front\UserController::class, 'makeSubscription'])->name('user.makeSubscription.store');

// Login Route
Route::get('user/login', [\App\Http\Controllers\Front\Auth\LoginController::class, 'index'])->name('user.login');
Route::post('user/login', [\App\Http\Controllers\Front\Auth\LoginController::class, 'authenticate'])->name('user.authenticate');
Route::get('user/logout', [\App\Http\Controllers\Front\Auth\LoginController::class, 'logout'])->name('user.logout');

//forgot password route
Route::get('user/forgot-password', [\App\Http\Controllers\Front\Auth\ForgotPasswordController::class, 'showForgotPasswordForm'])->name('user.forgot_password.create');
Route::post('user/forgot-password', [\App\Http\Controllers\Front\Auth\ForgotPasswordController::class, 'sendPasswordResetLink'])->name('user.forgot_password.send');
Route::get('user/reset-password/{token}', [\App\Http\Controllers\Front\Auth\ForgotPasswordController::class, 'resetPasswordForm'])->name('user.reset_password.create');
Route::post('user/reset-password', [\App\Http\Controllers\Front\Auth\ForgotPasswordController::class, 'passwordReset'])->name('user.reset_password.update');

Route::get('user/auth/{provider}', [\App\Http\Controllers\Front\Auth\LoginController::class, 'redirectToProvider'])->name('user.social.auth');
Route::get('user/auth/{provider}/callback', [\App\Http\Controllers\Front\Auth\LoginController::class, 'handleProviderCallback']);

Route::post('contact-request/store', [\App\Http\Controllers\Front\ContactRequestController::class, 'store'])->name('user.contact_request.store');

Route::get('user/subscription', [App\Http\Controllers\Front\SubscriptionPlanController::class, 'index'])->name('user.subscription');
Route::get('user/subscription/change-plan', [App\Http\Controllers\Front\SubscriptionPlanController::class, 'changePlan'])->name('user.subscription.chang_plan');
Route::post('user/subscription/store', [App\Http\Controllers\Front\SubscriptionPlanController::class, 'makeSubscription'])->name('user.subscription.store');

/*Route::get('/fillings-list', [App\Http\Controllers\Front\HomeController::class, 'fillingsList'])->name("app.filling-list");*/

Route::get('heat-map', [\App\Http\Controllers\Front\UserController::class, 'heatMap'])->name('heat-map');

Route::group(['middleware' => ['user.activated', 'auth']], function () {
// Route::middleware('auth')->group(function () {
    Route::get('user/profile', [\App\Http\Controllers\Front\UserController::class, 'profile'])->name('user.profile');
    Route::get('user/profile/edit', [\App\Http\Controllers\Front\UserController::class, 'editProfile'])->name('user.profile.edit');
    Route::post('user/profile/update', [\App\Http\Controllers\Front\UserController::class, 'updateProfile'])->name('user.profile.update');
    
});

Route::prefix('markets')->group(function () {
    Route::get('indices', function () {
        return view('livewire.markets.indices');
    })->name('markets.indices');

    Route::get('commodities', function () {
        return view('livewire.markets.commodities');
    })->name('markets.commodities');

    Route::get('forex', function () {
        
        return view('livewire.markets.forex');
    })->name('markets.forex');

    Route::get('bonds', function () {
        return view('livewire.markets.bonds');
    })->name('markets.bonds');

    Route::get('futures', function () {
        return view('livewire.markets.futures');
    })->name('markets.futures');

    Route::get('currencies', function () {
        return view('livewire.markets.currencies');
    })->name('markets.currencies');

    Route::get('stocks', function () {
        return view('livewire.markets.stocks');
    })->name('markets.stocks');

    Route::get('cryptocurrencies', function () {
        return view('livewire.markets.cryptocurrencies');
    })->name('markets.cryptocurrencies');
});

Route::prefix('calendar')->group(function () {
    Route::get('economic', function () {
        return view('livewire.calendar.economic');
    })->name('calendar.economic');
});


Route::get('stock-screener', function () {
    return view('livewire.stock-screener.widget');
})->name('stock-screener-widget');

Route::get('full-screen', function () {
    return view('livewire.partials.full-screen');
})->name('full-screen');

Route::prefix('widget')->group(function () {
    Route::get('stock-summary', function () {
        return view('livewire.widgets.stock-summary');
    })->name('widget.stock-summary');

    Route::get('company-profile', function () {
        return view('livewire.widgets.company-profile');
    })->name('widget.company-profile');

    Route::get('stocks-ticker', function () {
        return view('livewire.widgets.stock-ticker');
    })->name('stocks-ticker');
});

Route::get('search/{searchString?}', function ($searchString = '') {
    $res = MapperCikName::search($searchString)->first();
    dd($res);
});

Route::get('test', function (Request $request) {
    $zacksService = new \App\Services\ZacksService();
    $rows = $zacksService->getFinancials("JPM", 'A', 'balanceSheet');
    foreach ($rows as $date => $row) {
        $year = Carbon::parse($date);
        $ret = BalanceSheetStatement::query()->whereYear('date', $year)->where(['period' => 'FY', 'symbol' => "JPM"])->update($row);
        echo $ret . "<br/>";
    }
});

Route::get('full-screen/chart', function () {
    return view('front.charting');
})->name('full_chart');

Route::get('home-screen/chart', function () {
    return view('livewire.widgets.home-screen-chart');
})->name('home-screen.chart');

Route::get('/yeardatabs', [App\Http\Controllers\Front\HomeController::class, 'yearDatabs'])->name("year_databs");
Route::get('/yeardatais', [App\Http\Controllers\Front\HomeController::class, 'yearDatais'])->name("year_datais");
Route::get('/yeardatacf', [App\Http\Controllers\Front\HomeController::class, 'yearDatacf'])->name("year_datacf");
Route::get('/company/{searchKey}', [App\Http\Controllers\Front\HomeController::class, 'searchCompany'])->name("searchCompany");
Route::post('/select/company', [App\Http\Controllers\Front\HomeController::class, 'selectCompany'])->name("selectCompany");
Route::get('/select/company', [App\Http\Controllers\Front\HomeController::class, 'selectCompany'])->name("selectCompany");

Route::get('/funds', [App\Http\Controllers\Front\HomeController::class, 'holder']);




/* Network-Chat routes */
Route::get('upgrade-to-v3-4-0', function () {
    try {

        \Artisan::call('migrate', [
            '--path' => '/database/migrations/2020_10_19_133700_move_all_existing_devices_to_new_table.php',
            '--force' => true
        ]);

        return 'You are successfully migrated to v3.4.0';
    } catch (Exception $exception){
        return $exception->getMessage();
    }
});

Route::get('/upgrade-to-v4-3-0', function () {
    try {
        Artisan::call('db:seed', ['--class' => 'CreatePermissionSeeder']);

resources/views/admin/companies/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="breadcrumb-holder position-relative">
        <div class="container px-md-0">
            <ul class="breadcrumb az-content-breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                <li class="breadcrumb-item">Companies</li>
            </ul>
        </div>
    </div>
    <div class="az-content">
        <div class="container">
            <div class="az-content-body">
                @include('admin.layouts.partials.flash_messages')
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">

                                <div class="row">
                                    <div class="col-md-6">
                                        <h4>Add/Update Members for symbol # {{ $company->symbol }}</h4>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <a href="{{ route('admin.companies.index') }}" class="btn btn-warning">
                                            <i class="fa fa-arrow-left"></i>
                                            Back</a>
                                        <a href="{{ route('admin.companies.show',$company->id) }}"
                                           class="btn btn-info">View</a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('admin.companies.update',$company->id) }}" method="post">
                                    @method('PATCH')
                                    @csrf
                                    <div class="row mb-2">
                                        <div class="col-md-4">
                                            <label>Member Name</label>
                                        </div>
                                        <div class="col-md-2">
                                            <label>Is Chairman</label>
                                        </div>
                                        <div class="col-md-4">
                                            <a class="btn btn-success btn-sm text-white" id="add">
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                        <div class="col-md-2"></div>
                                    </div>
                                    <div id="members">
                                        @foreach($company->auditCommitteeMembers as $member)
                                            @php($randString = \Illuminate\Support\Str::random())
                                            <div class="row pb-2">
                                                <div class="col-md-4">
                                                    <input type="text" class="form-control members_name"
                                                           name="members_name[{{ $randString }}]" value="{{ $member->name }}"
                                                           placeholder="Member Name">
                                                </div>
                                                <div class="col-md-2">
                                                    <input type="radio" class="is_chairman" name="is_chairman"
                                                           {{ $member->is_chairman?'checked':null }}
                                                           value="{{ $randString }}">
                                                </div>
                                                <div class="col-md-4">
                                                    <a class="btn btn-danger btn-sm remove text-white">
                                                        <i class="fa fa-minus"></i>
                                                    </a>
                                                </div>
                                                <div class="col-md-2"></div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <div class="row">
                                        <div class="col-md-7 text-center">
                                            <button class="btn btn-success">Save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="display: none" id="member-template">
        <div class="row pb-2">
            <div class="col-md-4">
                <input type="text" class="form-control members_name" name="members_name[]" placeholder="Member Name">
            </div>
            <div class="col-md-2">
                <input type="radio" class="is_chairman" name="is_chairman" value="1">
            </div>
            <div class="col-md-4">
                <a class="btn btn-danger btn-sm remove text-white">
                    <i class="fa fa-minus"></i>
                </a>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        var memberTemplate = $('#member-template');
        var members = $('#members');
        $(document).ready(function () {
            addMember();
            $(document).on('click', '#add', function () {
                addMember();
            });
            $(document).on('click', '.remove', function () {
                $(this).closest('.row').remove();
            });
        });

        function addMember() {
            var tempId = makeid(10);
            var row = memberTemplate.find('.row').clone();
            row.find('.members_name').attr('name', 'members_name[' + tempId + ']');
            row.find('.is_chairman').attr('value', tempId);
            members.append(row);
        }

        function makeid(length) {
            var result = '';
            var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
            var charactersLength = characters.length;
            for (var i = 0; i < length; i++) {
                result += characters.charAt(Math.floor(Math.random() * charactersLength));
            }
            return result;
        }

    </script>


@endsection

resources/views/admin/companies/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="breadcrumb-holder position-relative">
        <div class="container px-md-0">
            <ul class="breadcrumb az-content-breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                <li class="breadcrumb-item">Companies</li>
            </ul>
        </div>
    </div>
    <div class="az-content">
        <div class="container">
            <div class="az-content-body">
                @include('admin.layouts.partials.flash_messages')
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header alert-primary">
                                <div class="row">
                                    <div class="col-md-6"><h3>Companies</h3></div>
                                    {{--<div class="col-md-6 text-right">
                                        <a href="{{ route('admin.companies.create') }}" class="btn btn-primary">Create</a>
                                    </div>--}}
                                </div>
                            </div>
                            <div class="card-body">
                                <table id="datatable" class="display responsive dataTable no-footer">
                                    <thead>
                                    <tr role="row">
                                        <th class="wd-15p sorting_asc">Symbol</th>
                                        <th class="wd-15p sorting_asc">CIK</th>
                                        <th class="wd-15p sorting_asc">Name</th>
                                        <th class="wd-15p sorting_asc">Sector</th>
                                        <th class="wd-15p sorting_asc">Head Quarter</th>
                                        <th class="wd-15p sorting_asc">Founded</th>
                                        <th class="wd-15p sorting_asc">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $(function () {
            var table = $('#datatable').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                scrollX: false,
                pageLength: 30,
                ajax: "{{ route('admin.companies.index') }}",
                columns: [
                    {data: 'symbol', name: 'symbol'},
                    {data: 'cik', name: 'cik'},
                    {data: 'name', name: 'name'},
                    {data: 'sector', name: 'sector'},
                    {data: 'headQuarter', name: 'headQuarter'},
                    {data: 'founded', name: 'founded'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });
    </script>

@endsection